<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Admin-PC" failures="1" tests="3" name="ThreeTest" time="42.787" errors="0" timestamp="22 Dec 2020 10:35:31 GMT">
  <testcase classname="AutomationPractice.MachineTest.InvalidSearchTest" name="invalidSearch" time="1.738"/>
  <testcase classname="AutomationPractice.MachineTest.DuplicaRegistrationTest" name="duplicate_registration" time="3.235"/>
  <testcase classname="AutomationPractice.MachineTest.CheckUpdateinvalidPersonalInfoTest" name="checkblankupdatepersonalinfo" time="7.755">
    <failure type="java.lang.AssertionError" message="expected [There is 1 error
The password you entered is incorrect.] but found [There is 1 error %n The password you entered is incorrect.]">
      <![CDATA[java.lang.AssertionError: expected [There is 1 error
The password you entered is incorrect.] but found [There is 1 error %n The password you entered is incorrect.]
at AutomationPractice.MachineTest.CheckUpdateinvalidPersonalInfoTest.checkblankupdatepersonalinfo(CheckUpdateinvalidPersonalInfoTest.java:30)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkblankupdatepersonalinfo -->
</testsuite> <!-- ThreeTest -->
